# Docs: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
      
  - package-ecosystem: "bundler"
    directory: "packages/smooth_app/android"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"     
      
  - package-ecosystem: "bundler"
    directory: "packages/smooth_app/ios"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  - package-ecosystem: "pub"
    directory: "/packages/smooth_app/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"

      
  - package-ecosystem: "pub"
    directory: "/packages/scanner/mlkit/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    directory: "/packages/scanner/shared/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    directory: "/packages/scanner/zxing/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
      
  - package-ecosystem: "pub"
    directory: "/packages/data_importer/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
      
  - package-ecosystem: "pub"
    directory: "/packages/app_store/shared/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
      
  - package-ecosystem: "pub"
    directory: "/packages/app_store/uri_store/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
      
  - package-ecosystem: "pub"
    directory: "/packages/data_importer_shared/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
      
  - package-ecosystem: "pub"
    directory: "/packages/app_store/google_play/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
      
  - package-ecosystem: "pub"
    directory: "/packages/app_store/apple_app_store/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"

#end
