name: app_store_apple_store
description: Apple App Store implementation
version: 0.0.1
publish_to: "none"

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  in_app_review: 2.0.9

  app_store_shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3
  openfoodfacts_flutter_lints:
    git:
      url: https://github.com/openfoodfacts/openfoodfacts_flutter_lints.git
      ref: e91bc71bccc317948dc769b8c5d55052d949ec2e